[package]
name = "ohg-bot-headers"
version = "0.1.0"
authors = ["Wolvereness <wesley.d.wolfe+git@gmail.com>"]
edition = "2018"

[dependencies]
wither = "0.9.0-alpha.2"
typetag = "*"
async-trait = "*"
arrayvec = "*"
